# Generated by Django 3.2.10 on 2022-01-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningType',
            new_name='CallBack',
        ),
    ]
