# Generated by Django 3.2.10 on 2021-12-10 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesInOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=2)),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.services')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('dateTime', models.DateTimeField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=100)),
                ('CleaningType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cleaningtypes')),
                ('ServicesInOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.servicesinorders')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.users')),
            ],
        ),
    ]
