# Generated by Django 3.2.10 on 2021-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesinorders',
            name='number',
            field=models.IntegerField(),
        ),
    ]
