# Generated by Django 3.2.10 on 2021-12-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_servicesinorders_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningTypes',
            new_name='CleaningType',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ServicesInOrders',
            new_name='ServicesInOrder',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='servicesinorder',
            old_name='Services',
            new_name='Service',
        ),
    ]
