# Generated by Django 3.2.10 on 2021-12-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(to='order.Status'),
        ),
    ]
