# Generated by Django 3.2.10 on 2021-12-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20211210_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ServicesInOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='ServicesInOrder',
            field=models.ManyToManyField(to='order.ServicesInOrder'),
        ),
    ]
