# Generated by Django 3.2.10 on 2021-12-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20211210_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ServicesInOrder',
        ),
    ]
