# Generated by Django 3.2.10 on 2021-12-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_servicesinorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesinorder',
            name='Order',
        ),
        migrations.AddField(
            model_name='order',
            name='ServicesInOrder',
            field=models.ManyToManyField(to='order.ServicesInOrder'),
        ),
    ]
