# Generated by Django 3.2.10 on 2021-12-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211216_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ServicesInOrder',
        ),
    ]
