# Generated by Django 3.2.10 on 2021-12-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_servicesinorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesinorder',
            name='Order',
        ),
        migrations.AddField(
            model_name='servicesinorder',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
